services:
  #====================================== Crud Resource Chain ==========================================================
  sympl.domain.cqrs.crud_resource_chain:
    public: true
    class: SymplBundle\Emailing\Domain\Command\CrudResourceChain

  SymplBundle\Emailing\Domain\Command\CrudResourceChain: "@sympl.domain.cqrs.crud_resource_chain"

  #====================================== EmailEvent ===================================================================
  sympl.domain.cqrs.create.email_event.handler:
    class: SymplBundle\Emailing\Domain\Command\Handler\CreateEmailEventHandler
    tags: ['sympl.mail_crud_resource']
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@sympl.domain.cqrs.factory.email_event"
      - "@sympl.domain.cqrs.factory.email_template"
      - "@sympl.domain.cqrs.factory.email_event_template"
      - "@sympl.domain.cqrs.factory.email_event_dto"

  sympl.domain.cqrs.update.email_event.handler:
    class: SymplBundle\Emailing\Domain\Command\Handler\UpdateEmailEventHandler
    tags: ['sympl.mail_crud_resource']
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@sympl.domain.cqrs.factory.email_event"
      - "@sympl.cqrs.domain.query.item_data_provider_chain"
      - "@sympl.domain.cqrs.factory.email_event_dto"

  sympl.domain.cqrs.delete.email_event.handler:
    class: SymplBundle\Emailing\Domain\Command\Handler\DeleteEmailEventHandler
    tags: ['sympl.mail_crud_resource']
    arguments:
      - "@doctrine.orm.entity_manager"

  #=================================Email template =====================================================================
  sympl.domain.cqrs.create.email_template.handler:
    class: SymplBundle\Emailing\Domain\Command\Handler\CreateEmailTemplateHandler
    tags: ['sympl.mail_crud_resource']
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@sympl.domain.cqrs.factory.email_template"
      - "@sympl.domain.cqrs.factory.email_event_template"
      - "@sympl.domain.cqrs.factory.email_template_dto"
      - "@sympl.cqrs.domain.query.item_data_provider_chain"

  sympl.domain.cqrs.update.email_template.handler:
    class: SymplBundle\Emailing\Domain\Command\Handler\UpdateEmailTemplateHandler
    tags: ['sympl.mail_crud_resource']
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@sympl.domain.cqrs.factory.email_template"
      - "@sympl.cqrs.domain.query.item_data_provider_chain"
      - "@sympl.domain.cqrs.factory.email_template_dto"

  sympl.domain.cqrs.delete.email_template.handler:
    class: SymplBundle\Emailing\Domain\Command\Handler\DeleteEmailTemplateHandler
    tags: ['sympl.mail_crud_resource']
    arguments:
      - "@doctrine.orm.entity_manager"

 #================================= Variables ============================================================================
  sympl.domain.cqrs.update.email_variable.handler:
    class: SymplBundle\Emailing\Domain\Command\Handler\UpdateEventVariableHandler
    tags: ['sympl.mail_crud_resource']
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@sympl.domain.cqrs.factory.email_variable"
      - "@sympl.cqrs.domain.query.item_data_provider_chain"
      - "@sympl.domain.cqrs.factory.email_variable_dto"

  sympl.domain.cqrs.delete.email_variable.handler:
    class: SymplBundle\Emailing\Domain\Command\Handler\DeleteVariableHandler
    tags: ['sympl.mail_crud_resource']
    arguments:
      - "@doctrine.orm.entity_manager"