services:
  #==================================== Item Data Provider =============================================================
  sympl.cqrs.domain.query.item_data_provider_chain:
    class: SymplBundle\Emailing\Domain\Query\DataProvider\ItemDataProviderChain
    public: true
  SymplBundle\Emailing\Domain\Query\DataProvider\ItemDataProviderChain: "@sympl.cqrs.domain.query.item_data_provider_chain"

  sympl.cqrs.domain.query.collection_data_provider_chain:
    class: SymplBundle\Emailing\Domain\Query\DataProvider\CollectionDataProviderChain
    public: true
  SymplBundle\Emailing\Domain\Query\DataProvider\CollectionDataProviderChain: "@sympl.cqrs.domain.query.collection_data_provider_chain"

  #================================= Email Event =======================================================================
  sympl.cqrs.domain.query.handler.item_handler:
    class: SymplBundle\Emailing\Domain\Query\Handler\ItemHandler
    tags: ['sympl.mail_handler']
    arguments:
      - "@sympl.cqrs.domain.query.factory.item_factory"
      - "@sympl.cqrs.domain.query.factory.transformer_by_repository_factory"

  sympl.cqrs.domain.query.handler.collection_handler:
    class: SymplBundle\Emailing\Domain\Query\Handler\CollectionHandler
    tags: ['sympl.mail_Collection_handler']
    arguments:
      - "@sympl.cqrs.domain.query.factory.collection_filter_factory"
      - "@sympl.cqrs.domain.query.factory.transformer_by_repository_factory"


#================================= Factories ===========================================================================
  sympl.cqrs.domain.query.factory.item_factory:
    class: SymplBundle\Emailing\Domain\Query\Factory\ItemQueryFactory

  sympl.cqrs.domain.query.factory.collection_filter_factory:
    class: SymplBundle\Emailing\Domain\Query\Factory\CollectionFilterFactory

  sympl.cqrs.domain.query.factory.transformer_by_repository_factory:
    class: SymplBundle\Emailing\Domain\Query\Factory\TransformerByRepositoryClassFactory
    arguments:
      - "@doctrine.orm.entity_manager"