# app/config/config.yml
imports:
  - { resource: parameters.yml }
  - { resource: security.yml }
  - { resource: services.yml }

framework:
  secret:          '%secret%'
  router:          { resource: '%kernel.project_dir%/config/routing.yml' }

doctrine:
  dbal:
    driver:   pdo_mysql
    user:     '%database_user%'
    password: '%database_password%'

# Twig Configuration
twig:
  debug:            '%kernel.debug%'
  strict_variables: '%kernel.debug%'
