services:
  sympl.domain.cqrs.factory.email_template:
    class: SymplBundle\Emailing\Domain\Factory\EmailTemplateFactory
    arguments:
      - "@doctrine.orm.entity_manager"

  sympl.domain.cqrs.factory.email_event:
    class: SymplBundle\Emailing\Domain\Factory\EmailEventFactory

  sympl.domain.cqrs.factory.email_variable:
    class: SymplBundle\Emailing\Domain\Factory\EmailEventVariableFactory

  sympl.domain.cqrs.factory.email_event_template:
    class: SymplBundle\Emailing\Domain\Factory\EmailEventTemplateFactory

  sympl.domain.cqrs.factory.email_template_dto:
    class: SymplBundle\Emailing\Domain\Factory\EmailTemplateDTOFactory

  sympl.domain.cqrs.factory.email_event_dto:
    class: SymplBundle\Emailing\Domain\Factory\EmailEventDTOFactory

  sympl.domain.cqrs.factory.email_variable_dto:
    class: SymplBundle\Emailing\Domain\Factory\EmailEventVariableDTOFactory

